services:
  - type: web
    name: rendiciones-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app_rendiciones.py --server.port 10000 --server.address 0.0.0.0"
